#!/bin/bash
# This is a simple build script, place your post-deploy but pre-start commands
# in this script.  This script gets executed directly, so it could be python,
# php, ruby, etc.

set -e

if [ -z $OPENSHIFT_MYSQL_DB_HOST ]
then
    echo 1>&2
    echo "Could not find mysql database.  Please run:" 1>&2
    echo "rhc-ctl-app -a $OPENSHIFT_APP_NAME -e add-mysql-5.1" 1>&2
    echo "then make a sample commit (add whitespace somewhere) and re-push" 1>&2
    echo 1>&2
    exit 5
fi

echo "Creating PaasRefApp database now"

# Confirm database exists, if not create it
#if ! /usr/bin/mysql -u "$OPENSHIFT_MYSQL_DB_USERNAME" —#password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" -e "select * from #actions;;" "$OPENSHIFT_APP_NAME" > /dev/null
#then
#    echo
#    echo "Schema not found!  Importing schema from .openshift/action_hooks/#PaaS_RefApp_DDL_DML.sql"
    echo

sleep 60

    /usr/bin/mysql -v -v -v -u "$OPENSHIFT_MYSQL_DB_USERNAME" --password="$OPENSHIFT_MYSQL_DB_PASSWORD" -h "$OPENSHIFT_MYSQL_DB_HOST" "$OPENSHIFT_APP_NAME" < "$OPENSHIFT_REPO_DIR/.openshift/action_hooks/PaaS_RefApp_DDL_DML.sql"
    echo
    echo "done."
#else
#    echo "Database found, skipping import."
#fi
